name = "appmaker"
version = "0.1.0"
license = "license"
author = "Lucas"
maintainer = "lucasbarbr@outlook.com"
copyright = "Copyright 2023, Lucas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

